tabelaPeriodica = {
    "h": {
        "nome": "Hidrogênio",
        "numero_atomico": 1,
        "massa_molar": 1.008,
        "grupo": "Não-metais",
        "descoberto_por": "Henry Cavendish",
        "camada_eletronica": "K1 L0 M0 N0 O0 P0 Q0 R0",
        "eletrons": 1,
        "protons": 1,
        "neutrons": 0
    },
    "he": {
        "nome": "Hélio",
        "numero_atomico": 2,
        "massa_molar": 4.0026,
        "grupo": "Gases Nobres",
        "descoberto_por": "Jules Janssen",
        "camada_eletronica": "K2 L0 M0 N0 O0 P0 Q0 R0",
        "eletrons": 2,
        "protons": 2,
        "neutrons": 2
    },
    "li": {
        "nome": "Lítio",
        "numero_atomico": 3,
        "massa_molar": 6.94,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Johan August Arfwedson",
        "camada_eletronica": "K2 L1 M0 N0 O0 P0 Q0 R0",
        "eletrons": 3,
        "protons": 3,
        "neutrons": 4
    },
    "be": {
        "nome": "Berílio",
        "numero_atomico": 4,
        "massa_molar": 9.0122,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Louis Nicolas Vauquelin",
        "camada_eletronica": "K2 L2 M0 N0 O0 P0 Q0 R0",
        "eletrons": 4,
        "protons": 4,
        "neutrons": 5
    },
    "b": {
        "nome": "Boro",
        "numero_atomico": 5,
        "massa_molar": 10.81,
        "grupo": "Semimetais",
        "descoberto_por": "Joseph Louis Gay-Lussac",
        "camada_eletronica": "K2 L3 M0 N0 O0 P0 Q0 R0",
        "eletrons": 5,
        "protons": 5,
        "neutrons": 6
    },
    "c": {
        "nome": "Carbono",
        "numero_atomico": 6,
        "massa_molar": 12.011,
        "grupo": "Não-metais",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L4 M0 N0 O0 P0 Q0 R0",
        "eletrons": 6,
        "protons": 6,
        "neutrons": 6
    },
    "n": {
        "nome": "Nitrogênio",
        "numero_atomico": 7,
        "massa_molar": 14.007,
        "grupo": "Não-metais",
        "descoberto_por": "Daniel Rutherford",
        "camada_eletronica": "K2 L5 M0 N0 O0 P0 Q0 R0",
        "eletrons": 7,
        "protons": 7,
        "neutrons": 7
    },
    "o": {
        "nome": "Oxigênio",
        "numero_atomico": 8,
        "massa_molar": 15.999,
        "grupo": "Não-metais",
        "descoberto_por": "Joseph Priestley",
        "camada_eletronica": "K2 L6 M0 N0 O0 P0 Q0 R0",
        "eletrons": 8,
        "protons": 8,
        "neutrons": 8
    },
    "f": {
        "nome": "Flúor",
        "numero_atomico": 9,
        "massa_molar": 18.998,
        "grupo": "Halogênios",
        "descoberto_por": "Henri Moissan",
        "camada_eletronica": "K2 L7 M0 N0 O0 P0 Q0 R0",
        "eletrons": 9,
        "protons": 9,
        "neutrons": 10
    },
    "ne": {
        "nome": "Neônio",
        "numero_atomico": 10,
        "massa_molar": 20.180,
        "grupo": "Gases Nobres",
        "descoberto_por": "Morris Travers",
        "camada_eletronica": "K2 L8 M0 N0 O0 P0 Q0 R0",
        "eletrons": 10,
        "protons": 10,
        "neutrons": 10
    },
    "na": {
        "nome": "Sódio",
        "numero_atomico": 11,
        "massa_molar": 22.990,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Humphry Davy",
        "camada_eletronica": "K2 L8 M1 N0 O0 P0 Q0 R0",
        "eletrons": 11,
        "protons": 11,
        "neutrons": 12
    },
    "mg": {
        "nome": "Magnésio",
        "numero_atomico": 12,
        "massa_molar": 24.305,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Humphry Davy",
        "camada_eletronica": "K2 L8 M2 N0 O0 P0 Q0 R0",
        "eletrons": 12,
        "protons": 12,
        "neutrons": 12
    },
    "al": {
        "nome": "Alumínio",
        "numero_atomico": 13,
        "massa_molar": 26.982,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Hans Christian Ørsted",
        "camada_eletronica": "K2 L8 M3 N0 O0 P0 Q0 R0",
        "eletrons": 13,
        "protons": 13,
        "neutrons": 14
    },
    "si": {
        "nome": "Silício",
        "numero_atomico": 14,
        "massa_molar": 28.085,
        "grupo": "Semimetais",
        "descoberto_por": "Jöns Jacob Berzelius",
        "camada_eletronica": "K2 L8 M4 N0 O0 P0 Q0 R0",
        "eletrons": 14,
        "protons": 14,
        "neutrons": 14
    },
    "p": {
        "nome": "Fósforo",
        "numero_atomico": 15,
        "massa_molar": 30.974,
        "grupo": "Não-metais",
        "descoberto_por": "Hennig Brand",
        "camada_eletronica": "K2 L8 M5 N0 O0 P0 Q0 R0",
        "eletrons": 15,
        "protons": 15,
        "neutrons": 16
    },
    "s": {
        "nome": "Enxofre",
        "numero_atomico": 16,
        "massa_molar": 32.06,
        "grupo": "Não-metais",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M6 N0 O0 P0 Q0 R0",
        "eletrons": 16,
        "protons": 16,
        "neutrons": 16
    },
    "cl": {
        "nome": "Cloro",
        "numero_atomico": 17,
        "massa_molar": 35.45,
        "grupo": "Halogênios",
        "descoberto_por": "Carl Wilhelm Scheele",
        "camada_eletronica": "K2 L8 M7 N0 O0 P0 Q0 R0",
        "eletrons": 17,
        "protons": 17,
        "neutrons": 18
    },
    "ar": {
        "nome": "Argônio",
        "numero_atomico": 18,
        "massa_molar": 39.948,
        "grupo": "Gases Nobres",
        "descoberto_por": "Lord Rayleigh",
        "camada_eletronica": "K2 L8 M8 N0 O0 P0 Q0 R0",
        "eletrons": 18,
        "protons": 18,
        "neutrons": 22
    },
    "k": {
        "nome": "Potássio",
        "numero_atomico": 19,
        "massa_molar": 39.098,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Humphry Davy",
        "camada_eletronica": "K2 L8 M8 N1 O0 P0 Q0 R0",
        "eletrons": 19,
        "protons": 19,
        "neutrons": 20
    },
    "ca": {
        "nome": "Cálcio",
        "numero_atomico": 20,
        "massa_molar": 40.078,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Humphry Davy",
        "camada_eletronica": "K2 L8 M8 N2 O0 P0 Q0 R0",
        "eletrons": 20,
        "protons": 20,
        "neutrons": 20
    },
    "sc": {
        "nome": "Escândio",
        "numero_atomico": 21,
        "massa_molar": 44.956,
        "grupo": "Metais de Transição",
        "descoberto_por": "Lars Fredrik Nilson",
        "camada_eletronica": "K2 L8 M9 N2 O0 P0 Q0 R0",
        "eletrons": 21,
        "protons": 21,
        "neutrons": 24
    },
    "ti": {
        "nome": "Titânio",
        "numero_atomico": 22,
        "massa_molar": 47.867,
        "grupo": "Metais de Transição",
        "descoberto_por": "William Gregor",
        "camada_eletronica": "K2 L8 M10 N2 O0 P0 Q0 R0",
        "eletrons": 22,
        "protons": 22,
        "neutrons": 26
    },
    "v": {
        "nome": "Vanádio",
        "numero_atomico": 23,
        "massa_molar": 50.942,
        "grupo": "Metais de Transição",
        "descoberto_por": "Andrés Manuel del Río",
        "camada_eletronica": "K2 L8 M11 N2 O0 P0 Q0 R0",
        "eletrons": 23,
        "protons": 23,
        "neutrons": 28
    },
    "cr": {
        "nome": "Cromo",
        "numero_atomico": 24,
        "massa_molar": 51.996,
        "grupo": "Metais de Transição",
        "descoberto_por": "Louis Nicolas Vauquelin",
        "camada_eletronica": "K2 L8 M13 N1 O0 P0 Q0 R0",
        "eletrons": 24,
        "protons": 24,
        "neutrons": 28
    },
    "mn": {
        "nome": "Manganês",
        "numero_atomico": 25,
        "massa_molar": 54.938,
        "grupo": "Metais de Transição",
        "descoberto_por": "Carl Wilhelm Scheele",
        "camada_eletronica": "K2 L8 M13 N2 O0 P0 Q0 R0",
        "eletrons": 25,
        "protons": 25,
        "neutrons": 30
    },
    "fe": {
        "nome": "Ferro",
        "numero_atomico": 26,
        "massa_molar": 55.845,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M14 N2 O0 P0 Q0 R0",
        "eletrons": 26,
        "protons": 26,
        "neutrons": 30
    },
    "co": {
        "nome": "Cobalto",
        "numero_atomico": 27,
        "massa_molar": 58.933,
        "grupo": "Metais de Transição",
        "descoberto_por": "Georg Brandt",
        "camada_eletronica": "K2 L8 M15 N2 O0 P0 Q0 R0",
        "eletrons": 27,
        "protons": 27,
        "neutrons": 32
    },
    "ni": {
        "nome": "Níquel",
        "numero_atomico": 28,
        "massa_molar": 58.693,
        "grupo": "Metais de Transição",
        "descoberto_por": "Axel Fredrik Cronstedt",
        "camada_eletronica": "K2 L8 M16 N2 O0 P0 Q0 R0",
        "eletrons": 28,
        "protons": 28,
        "neutrons": 31
    },
    "cu": {
        "nome": "Cobre",
        "numero_atomico": 29,
        "massa_molar": 63.546,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N1 O0 P0 Q0 R0",
        "eletrons": 29,
        "protons": 29,
        "neutrons": 35
    },
    "zn": {
        "nome": "Zinco",
        "numero_atomico": 30,
        "massa_molar": 65.38,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido na Índia antiga",
        "camada_eletronica": "K2 L8 M18 N2 O0 P0 Q0 R0",
        "eletrons": 30,
        "protons": 30,
        "neutrons": 35
    },
    "ga": {
        "nome": "Gálio",
        "numero_atomico": 31,
        "massa_molar": 69.723,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Paul-Émile Lecoq de Boisbaudran",
        "camada_eletronica": "K2 L8 M18 N3 O0 P0 Q0 R0",
        "eletrons": 31,
        "protons": 31,
        "neutrons": 39
    },
    "ge" : {
        "nome": "Germânio",
        "numero_atomico": 32,
        "massa_molar": 72.6298,
        "grupo": "Semimetais",
        "descoberto_por": "Clemens Alexander Winkler",
        "camada_eletronica": "K2 L8 M18 N4 O0 P0 Q0 R0",
        "eletrons": 32,
        "protons": 32,
        "neutrons": 41
    },
    "as": {
        "nome": "Arsênio",
        "numero_atomico": 33,
        "massa_molar": 74.922,
        "grupo": "Semimetais",
        "descoberto_por": "Albertus Magnus",
        "camada_eletronica": "K2 L8 M18 N5 O0 P0 Q0 R0",
        "eletrons": 33,
        "protons": 33,
        "neutrons": 42
    },
    "se": {
        "nome": "Selênio",
        "numero_atomico": 34,
        "massa_molar": 78.971,
        "grupo": "Não-metais",
        "descoberto_por": "Jöns Jacob Berzelius",
        "camada_eletronica": "K2 L8 M18 N6 O0 P0 Q0 R0",
        "eletrons": 34,
        "protons": 34,
        "neutrons": 45
    },
    "br": {
        "nome": "Bromo",
        "numero_atomico": 35,
        "massa_molar": 79.904,
        "grupo": "Halogênios",
        "descoberto_por": "Antoine Jérôme Balard",
        "camada_eletronica": "K2 L8 M18 N7 O0 P0 Q0 R0",
        "eletrons": 35,
        "protons": 35,
        "neutrons": 45
    },
    "kr": {
        "nome": "Criptônio",
        "numero_atomico": 36,
        "massa_molar": 83.798,
        "grupo": "Gases Nobres",
        "descoberto_por": "William Ramsay",
        "camada_eletronica": "K2 L8 M18 N8 O0 P0 Q0 R0",
        "eletrons": 36,
        "protons": 36,
        "neutrons": 48
    },
    "rb": {
        "nome": "Rubídio",
        "numero_atomico": 37,
        "massa_molar": 85.468,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Robert Bunsen",
        "camada_eletronica": "K2 L8 M18 N8 O1 P0 Q0 R0",
        "eletrons": 37,
        "protons": 37,
        "neutrons": 48
    },
    "sr": {
        "nome": "Estrôncio",
        "numero_atomico": 38,
        "massa_molar": 87.62,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Adair Crawford",
        "camada_eletronica": "K2 L8 M18 N8 O2 P0 Q0 R0",
        "eletrons": 38,
        "protons": 38,
        "neutrons": 50
    },
    "y": {
        "nome": "Ítrio",
        "numero_atomico": 39,
        "massa_molar": 88.906,
        "grupo": "Metais de Transição",
        "descoberto_por": "Johan Gadolin",
        "camada_eletronica": "K2 L8 M18 N9 O2 P0 Q0 R0",
        "eletrons": 39,
        "protons": 39,
        "neutrons": 50
    },
    "zr": {
        "nome": "Zircônio",
        "numero_atomico": 40,
        "massa_molar": 91.224,
        "grupo": "Metais de Transição",
        "descoberto_por": "Martin Heinrich Klaproth",
        "camada_eletronica": "K2 L8 M18 N10 O2 P0 Q0 R0",
        "eletrons": 40,
        "protons": 40,
        "neutrons": 51
    },
    "nb": {
        "nome": "Nióbio",
        "numero_atomico": 41,
        "massa_molar": 92.906,
        "grupo": "Metais de Transição",
        "descoberto_por": "Charles Hatchett",
        "camada_eletronica": "K2 L8 M18 N12 O1 P0 Q0 R0",
        "eletrons": 41,
        "protons": 41,
        "neutrons": 52
    },
    "mo": {
        "nome": "Molibdênio",
        "numero_atomico": 42,
        "massa_molar": 95.95,
        "grupo": "Metais de Transição",
        "descoberto_por": "Carl Wilhelm Scheele",
        "camada_eletronica": "K2 L8 M18 N13 O1 P0 Q0 R0",
        "eletrons": 42,
        "protons": 42,
        "neutrons": 54
    },
    "tc": {
        "nome": "Tecnécio",
        "numero_atomico": 43,
        "massa_molar": 98,
        "grupo": "Metais de Transição",
        "descoberto_por": "Emilio Segrè",
        "camada_eletronica": "K2 L8 M18 N13 O2 P0 Q0 R0",
        "eletrons": 43,
        "protons": 43,
        "neutrons": 55
    },
    "ru": {
        "nome": "Rutênio",
        "numero_atomico": 44,
        "massa_molar": 101.07,
        "grupo": "Metais de Transição",
        "descoberto_por": "Karl Ernst Claus",
        "camada_eletronica": "K2 L8 M18 N15 O1 P0 Q0 R0",
        "eletrons": 44,
        "protons": 44,
        "neutrons": 57
    },
    "rh": {
        "nome": "Ródio",
        "numero_atomico": 45,
        "massa_molar": 102.91,
        "grupo": "Metais de Transição",
        "descoberto_por": "William Hyde Wollaston",
        "camada_eletronica": "K2 L8 M18 N16 O1 P0 Q0 R0",
        "eletrons": 45,
        "protons": 45,
        "neutrons": 58
    },
    "pd": {
        "nome": "Paládio",
        "numero_atomico": 46,
        "massa_molar": 106.42,
        "grupo": "Metais de Transição",
        "descoberto_por": "William Hyde Wollaston",
        "camada_eletronica": "K2 L8 M18 N18 O0 P0 Q0 R0",
        "eletrons": 46,
        "protons": 46,
        "neutrons": 60
    },
    "ag": {
        "nome": "Prata",
        "numero_atomico": 47,
        "massa_molar": 107.87,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N18 O1 P0 Q0 R0",
        "eletrons": 47,
        "protons": 47,
        "neutrons": 61
    },
    "cd": {
        "nome": "Cádmio",
        "numero_atomico": 48,
        "massa_molar": 112.41,
        "grupo": "Metais de Transição",
        "descoberto_por": "Friedrich Stromeyer",
        "camada_eletronica": "K2 L8 M18 N18 O2 P0 Q0 R0",
        "eletrons": 48,
        "protons": 48,
        "neutrons": 64
    },
    "in": {
        "nome": "Índio",
        "numero_atomico": 49,
        "massa_molar": 114.82,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Ferdinand Reich",
        "camada_eletronica": "K2 L8 M18 N18 O3 P0 Q0 R0",
        "eletrons": 49,
        "protons": 49,
        "neutrons": 66
    },
    "sn": {
        "nome": "Estanho",
        "numero_atomico": 50,
        "massa_molar": 118.71,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N18 O4 P0 Q0 R0",
        "eletrons": 50,
        "protons": 50,
        "neutrons": 69
    },
    "sb": {
        "nome": "Antimônio",
        "numero_atomico": 51,
        "massa_molar": 121.76,
        "grupo": "Semimetais",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N18 O5 P0 Q0 R0",
        "eletrons": 51,
        "protons": 51,
        "neutrons": 71
    },
    "te": {
        "nome": "Telúrio",
        "numero_atomico": 52,
        "massa_molar": 127.60,
        "grupo": "Semimetais",
        "descoberto_por": "Franz-Joseph Müller von Reichenstein",
        "camada_eletronica": "K2 L8 M18 N18 O6 P0 Q0 R0",
        "eletrons": 52,
        "protons": 52,
        "neutrons": 76
    },
    "i": {
        "nome": "Iodo",
        "numero_atomico": 53,
        "massa_molar": 126.90,
        "grupo": "Halogênios",
        "descoberto_por": "Bernard Courtois",
        "camada_eletronica": "K2 L8 M18 N18 O7 P0 Q0 R0",
        "eletrons": 53,
        "protons": 53,
        "neutrons": 74
    },
    "xe": {
        "nome": "Xenônio",
        "numero_atomico": 54,
        "massa_molar": 131.29,
        "grupo": "Gases Nobres",
        "descoberto_por": "William Ramsay",
        "camada_eletronica": "K2 L8 M18 N18 O8 P0 Q0 R0",
        "eletrons": 54,
        "protons": 54,
        "neutrons": 77
    },
    "cs": {
        "nome": "Césio",
        "numero_atomico": 55,
        "massa_molar": 132.91,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Robert Bunsen",
        "camada_eletronica": "K2 L8 M18 N18 O8 P1 Q0 R0",
        "eletrons": 55,
        "protons": 55,
        "neutrons": 78
    },
    "ba": {
        "nome": "Bário",
        "numero_atomico": 56,
        "massa_molar": 137.33,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Carl Wilhelm Scheele",
        "camada_eletronica": "K2 L8 M18 N18 O8 P2 Q0 R0",
        "eletrons": 56,
        "protons": 56,
        "neutrons": 81
    },
    "la": {
        "nome": "Lantânio",
        "numero_atomico": 57,
        "massa_molar": 138.91,
        "grupo": "Lantanídeos",
        "descoberto_por": "Carl Gustaf Mosander",
        "camada_eletronica": "K2 L8 M18 N18 O9 P2 Q0 R0",
        "eletrons": 57,
        "protons": 57,
        "neutrons": 82
    },
    "ce": {
        "nome": "Cério",
        "numero_atomico": 58,
        "massa_molar": 140.12,
        "grupo": "Lantanídeos",
        "descoberto_por": "Martin Heinrich Klaproth",
        "camada_eletronica": "K2 L8 M18 N19 O9 P2 Q0 R0",
        "eletrons": 58,
        "protons": 58,
        "neutrons": 82
    },
    "pr": {
        "nome": "Praseodímio",
        "numero_atomico": 59,
        "massa_molar": 140.91,
        "grupo": "Lantanídeos",
        "descoberto_por": "Carl Auer von Welsbach",
        "camada_eletronica": "K2 L8 M18 N21 O8 P2 Q0 R0",
        "eletrons": 59,
        "protons": 59,
        "neutrons": 82
    },
    "nd": {
        "nome": "Neodímio",
        "numero_atomico": 60,
        "massa_molar": 144.24,
        "grupo": "Lantanídeos",
        "descoberto_por": "Carl Auer von Welsbach",
        "camada_eletronica": "K2 L8 M18 N22 O8 P2 Q0 R0",
        "eletrons": 60,
        "protons": 60,
        "neutrons": 84
    },
    "pm": {
        "nome": "Promécio",
        "numero_atomico": 61,
        "massa_molar": 145,
        "grupo": "Lantanídeos",
        "descoberto_por": "Jacob A. Marinsky",
        "camada_eletronica": "K2 L8 M18 N23 O8 P2 Q0 R0",
        "eletrons": 61,
        "protons": 61,
        "neutrons": 84
    },
    "sm": {
        "nome": "Samário",
        "numero_atomico": 62,
        "massa_molar": 150.36,
        "grupo": "Lantanídeos",
        "descoberto_por": "Paul Émile Lecoq de Boisbaudran",
        "camada_eletronica": "K2 L8 M18 N24 O8 P2 Q0 R0",
        "eletrons": 62,
        "protons": 62,
        "neutrons": 88
    },
    "eu": {
        "nome": "Európio",
        "numero_atomico": 63,
        "massa_molar": 151.96,
        "grupo": "Lantanídeos",
        "descoberto_por": "Eugène-Anatole Demarçay",
        "camada_eletronica": "K2 L8 M18 N25 O8 P2 Q0 R0",
        "eletrons": 63,
        "protons": 63,
        "neutrons": 89
    },
    "gd": {
        "nome": "Gadolínio",
        "numero_atomico": 64,
        "massa_molar": 157.25,
        "grupo": "Lantanídeos",
        "descoberto_por": "Jean Charles Galissard de Marignac",
        "camada_eletronica": "K2 L8 M18 N25 O9 P2 Q0 R0",
        "eletrons": 64,
        "protons": 64,
        "neutrons": 93
    },
    "tb": {
        "nome": "Térbio",
        "numero_atomico": 65,
        "massa_molar": 158.93,
        "grupo": "Lantanídeos",
        "descoberto_por": "Carl Gustaf Mosander",
        "camada_eletronica": "K2 L8 M18 N27 O8 P2 Q0 R0",
        "eletrons": 65,
        "protons": 65,
        "neutrons": 94
    },
    "dy": {
        "nome": "Disprósio",
        "numero_atomico": 66,
        "massa_molar": 162.50,
        "grupo": "Lantanídeos",
        "descoberto_por": "Paul Émile Lecoq de Boisbaudran",
        "camada_eletronica": "K2 L8 M18 N28 O8 P2 Q0 R0",
        "eletrons": 66,
        "protons": 66,
        "neutrons": 97
    },
    "ho": {
        "nome": "Hólmio",
        "numero_atomico": 67,
        "massa_molar": 164.93,
        "grupo": "Lantanídeos",
        "descoberto_por": "Marc Delafontaine",
        "camada_eletronica": "K2 L8 M18 N29 O8 P2 Q0 R0",
        "eletrons": 67,
        "protons": 67,
        "neutrons": 98
    },
    "er": {
        "nome": "Érbio",
        "numero_atomico": 68,
        "massa_molar": 167.26,
        "grupo": "Lantanídeos",
        "descoberto_por": "Carl Gustaf Mosander",
        "camada_eletronica": "K2 L8 M18 N30 O8 P2 Q0 R0",
        "eletrons": 68,
        "protons": 68,
        "neutrons": 99
    },
    "tm": {
        "nome": "Túlio",
        "numero_atomico": 69,
        "massa_molar": 168.93,
        "grupo": "Lantanídeos",
        "descoberto_por": "Per Teodor Cleve",
        "camada_eletronica": "K2 L8 M18 N31 O8 P2 Q0 R0",
        "eletrons": 69,
        "protons": 69,
        "neutrons": 100
    },
    "yb": {
        "nome": "Itérbio",
        "numero_atomico": 70,
        "massa_molar": 173.05,
        "grupo": "Lantanídeos",
        "descoberto_por": "Jean Charles Galissard de Marignac",
        "camada_eletronica": "K2 L8 M18 N32 O8 P2 Q0 R0",
        "eletrons": 70,
        "protons": 70,
        "neutrons": 103
    },
    "lu": {
        "nome": "Lutécio",
        "numero_atomico": 71,
        "massa_molar": 174.97,
        "grupo": "Lantanídeos",
        "descoberto_por": "Georges Urbain",
        "camada_eletronica": "K2 L8 M18 N32 O9 P2 Q0 R0",
        "eletrons": 71,
        "protons": 71,
        "neutrons": 104
    },
    "hf": {
        "nome": "Háfnio",
        "numero_atomico": 72,
        "massa_molar": 178.49,
        "grupo": "Metais de Transição",
        "descoberto_por": "Dirk Coster",
        "camada_eletronica": "K2 L8 M18 N32 O10 P2 Q0 R0",
        "eletrons": 72,
        "protons": 72,
        "neutrons": 106
    },
    "ta": {
        "nome": "Tântalo",
        "numero_atomico": 73,
        "massa_molar": 180.95,
        "grupo": "Metais de Transição",
        "descoberto_por": "Anders Ekeberg",
        "camada_eletronica": "K2 L8 M18 N32 O11 P2 Q0 R0",
        "eletrons": 73,
        "protons": 73,
        "neutrons": 108
    },
    "w": {
        "nome": "Tungstênio",
        "numero_atomico": 74,
        "massa_molar": 183.84,
        "grupo": "Metais de Transição",
        "descoberto_por": "Fausto Elhuyar",
        "camada_eletronica": "K2 L8 M18 N32 O12 P2 Q0 R0",
        "eletrons": 74,
        "protons": 74,
        "neutrons": 110
    },
    "re": {
        "nome": "Rênio",
        "numero_atomico": 75,
        "massa_molar": 186.21,
        "grupo": "Metais de Transição",
        "descoberto_por": "Walter Noddack",
        "camada_eletronica": "K2 L8 M18 N32 O13 P2 Q0 R0",
        "eletrons": 75,
        "protons": 75,
        "neutrons": 111
    },
    "os": {
        "nome": "Ósmio",
        "numero_atomico": 76,
        "massa_molar": 190.23,
        "grupo": "Metais de Transição",
        "descoberto_por": "Smithson Tennant",
        "camada_eletronica": "K2 L8 M18 N32 O14 P2 Q0 R0",
        "eletrons": 76,
        "protons": 76,
        "neutrons": 114
    },
    "ir": {
        "nome": "Irídio",
        "numero_atomico": 77,
        "massa_molar": 192.22,
        "grupo": "Metais de Transição",
        "descoberto_por": "Smithson Tennant",
        "camada_eletronica": "K2 L8 M18 N32 O15 P2 Q0 R0",
        "eletrons": 77,
        "protons": 77,
        "neutrons": 115
    },
    "pt": {
        "nome": "Platina",
        "numero_atomico": 78,
        "massa_molar": 195.08,
        "grupo": "Metais de Transição",
        "descoberto_por": "Antonio de Ulloa",
        "camada_eletronica": "K2 L8 M18 N32 O17 P1 Q0 R0",
        "eletrons": 78,
        "protons": 78,
        "neutrons": 117
    },
    "au": {
        "nome": "Ouro",
        "numero_atomico": 79,
        "massa_molar": 196.97,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N32 O18 P1 Q0 R0",
        "eletrons": 79,
        "protons": 79,
        "neutrons": 118
    },
    "hg": {
        "nome": "Mercúrio",
        "numero_atomico": 80,
        "massa_molar": 200.59,
        "grupo": "Metais de Transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N32 O18 P2 Q0 R0",
        "eletrons": 80,
        "protons": 80,
        "neutrons": 121
    },
    "tl": {
        "nome": "Tálio",
        "numero_atomico": 81,
        "massa_molar": 204.38,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "William Crookes",
        "camada_eletronica": "K2 L8 M18 N32 O18 P3 Q0 R0",
        "eletrons": 81,
        "protons": 81,
        "neutrons": 123
    },
    "pb": {
        "nome": "Chumbo",
        "numero_atomico": 82,
        "massa_molar": 207.2,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Conhecido desde a antiguidade",
        "camada_eletronica": "K2 L8 M18 N32 O18 P4 Q0 R0",
        "eletrons": 82,
        "protons": 82,
        "neutrons": 125
    },
    "bi": {
        "nome": "Bismuto",
        "numero_atomico": 83,
        "massa_molar": 208.98,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Claude François Geoffroy",
        "camada_eletronica": "K2 L8 M18 N32 O18 P5 Q0 R0",
        "eletrons": 83,
        "protons": 83,
        "neutrons": 126
    },
    "po": {
        "nome": "Polônio",
        "numero_atomico": 84,
        "massa_molar": 209,
        "grupo": "Semimetais",
        "descoberto_por": "Marie Curie",
        "camada_eletronica": "K2 L8 M18 N32 O18 P6 Q0 R0",
        "eletrons": 84,
        "protons": 84,
        "neutrons": 125
    },
    "at": {
        "nome": "Astato",
        "numero_atomico": 85,
        "massa_molar": 210,
        "grupo": "Halogênios",
        "descoberto_por": "Dale R. Corson",
        "camada_eletronica": "K2 L8 M18 N32 O18 P7 Q0 R0",
        "eletrons": 85,
        "protons": 85,
        "neutrons": 125
    },
    "rn": {
        "nome": "Radônio",
        "numero_atomico": 86,
        "massa_molar": 222,
        "grupo": "Gases Nobres",
        "descoberto_por": "Friedrich Ernst Dorn",
        "camada_eletronica": "K2 L8 M18 N32 O18 P8 Q0 R0",
        "eletrons": 86,
        "protons": 86,
        "neutrons": 136
    },
    "fr": {
        "nome": "Frâncio",
        "numero_atomico": 87,
        "massa_molar": 223,
        "grupo": "Metais Alcalinos",
        "descoberto_por": "Marguerite Perey",
        "camada_eletronica": "K2 L8 M18 N32 O18 P8 Q1 R0",
        "eletrons": 87,
        "protons": 87,
        "neutrons": 136
    },
    "ra": {
        "nome": "Rádio",
        "numero_atomico": 88,
        "massa_molar": 226,
        "grupo": "Metais Alcalinos Terrosos",
        "descoberto_por": "Marie Curie",
        "camada_eletronica": "K2 L8 M18 N32 O18 P8 Q2 R0",
        "eletrons": 88,
        "protons": 88,
        "neutrons": 138
    },
    "ac": {
        "nome": "Actínio",
        "numero_atomico": 89,
        "massa_molar": 227,
        "grupo": "Actinídeos",
        "descoberto_por": "André-Louis Debierne",
        "camada_eletronica": "K2 L8 M18 N32 O18 P9 Q2 R0",
        "eletrons": 89,
        "protons": 89,
        "neutrons": 138
    },
    "th": {
        "nome": "Tório",
        "numero_atomico": 90,
        "massa_molar": 232.04,
        "grupo": "Actinídeos",
        "descoberto_por": "Jöns Jacob Berzelius",
        "camada_eletronica": "K2 L8 M18 N32 O18 P10 Q2 R0",
        "eletrons": 90,
        "protons": 90,
        "neutrons": 142
    },
    "pa": {
        "nome": "Protactínio",
        "numero_atomico": 91,
        "massa_molar": 231.04,
        "grupo": "Actinídeos",
        "descoberto_por": "Kasimir Fajans",
        "camada_eletronica": "K2 L8 M18 N32 O20 P9 Q2 R0",
        "eletrons": 91,
        "protons": 91,
        "neutrons": 140
    },
    "u": {
        "nome": "Urânio",
        "numero_atomico": 92,
        "massa_molar": 238.03,
        "grupo": "Actinídeos",
        "descoberto_por": "Martin Heinrich Klaproth",
        "camada_eletronica": "K2 L8 M18 N32 O21 P9 Q2 R0",
        "eletrons": 92,
        "protons": 92,
        "neutrons": 146
    },
    "np": {
        "nome": "Neptúnio",
        "numero_atomico": 93,
        "massa_molar": 237,
        "grupo": "Actinídeos",
        "descoberto_por": "Edwin McMillan",
        "camada_eletronica": "K2 L8 M18 N32 O22 P9 Q2 R0",
        "eletrons": 93,
        "protons": 93,
        "neutrons": 144
    },
    "pu": {
        "nome": "Plutônio",
        "numero_atomico": 94,
        "massa_molar": 244,
        "grupo": "Actinídeos",
        "descoberto_por": "Glenn T. Seaborg",
        "camada_eletronica": "K2 L8 M18 N32 O24 P8 Q2 R0",
        "eletrons": 94,
        "protons": 94,
        "neutrons": 150
    },
    "am": {
        "nome": "Amerício",
        "numero_atomico": 95,
        "massa_molar": 243,
        "grupo": "Actinídeos",
        "descoberto_por": "Glenn T. Seaborg",
        "camada_eletronica": "K2 L8 M18 N32 O25 P8 Q2 R0",
        "eletrons": 95,
        "protons": 95,
        "neutrons": 148
    },
    "cm": {
        "nome": "Cúrio",
        "numero_atomico": 96,
        "massa_molar": 247,
        "grupo": "Actinídeos",
        "descoberto_por": "Glenn T. Seaborg",
        "camada_eletronica": "K2 L8 M18 N32 O25 P9 Q2 R0",
        "eletrons": 96,
        "protons": 96,
        "neutrons": 151
    },
    "bk": {
        "nome": "Berquélio",
        "numero_atomico": 97,
        "massa_molar": 247,
        "grupo": "Actinídeos",
        "descoberto_por": "Glenn T. Seaborg",
        "camada_eletronica": "K2 L8 M18 N32 O27 P8 Q2 R0",
        "eletrons": 97,
        "protons": 97,
        "neutrons": 150
    },
    "cf": {
        "nome": "Califórnio",
        "numero_atomico": 98,
        "massa_molar": 251,
        "grupo": "Actinídeos",
        "descoberto_por": "Stanley G. Thompson",
        "camada_eletronica": "K2 L8 M18 N32 O28 P8 Q2 R0",
        "eletrons": 98,
        "protons": 98,
        "neutrons": 153
    },
    "es": {
        "nome": "Einstênio",
        "numero_atomico": 99,
        "massa_molar": 252,
        "grupo": "Actinídeos",
        "descoberto_por": "Albert Ghiorso",
        "camada_eletronica": "K2 L8 M18 N32 O29 P8 Q2 R0",
        "eletrons": 99,
        "protons": 99,
        "neutrons": 153
    },
    "fm": {
        "nome": "Férmio",
        "numero_atomico": 100,
        "massa_molar": 257,
        "grupo": "Actinídeos",
        "descoberto_por": "Albert Ghiorso",
        "camada_eletronica": "K2 L8 M18 N32 O30 P8 Q2 R0",
        "eletrons": 100,
        "protons": 100,
        "neutrons": 157
    },
    "md": {
        "nome": "Mendelévio",
        "numero_atomico": 101,
        "massa_molar": 258,
        "grupo": "Actinídeos",
        "descoberto_por": "Albert Ghiorso",
        "camada_eletronica": "K2 L8 M18 N32 O31 P8 Q2 R0",
        "eletrons": 101,
        "protons": 101,
        "neutrons": 157
    },
    "no": {
        "nome": "Nobélio",
        "numero_atomico": 102,
        "massa_molar": 259,
        "grupo": "Actinídeos",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P8 Q2 R0",
        "eletrons": 102,
        "protons": 102,
        "neutrons": 157
    },
    "lr": {
        "nome": "Laurêncio",
        "numero_atomico": 103,
        "massa_molar": 266,
        "grupo": "Actinídeos",
        "descoberto_por": "Albert Ghiorso",
        "camada_eletronica": "K2 L8 M18 N32 O32 P8 Q3 R0",
        "eletrons": 103,
        "protons": 103,
        "neutrons": 163
    },
    "rf": {
        "nome": "Rutherfórdio",
        "numero_atomico": 104,
        "massa_molar": 267,
        "grupo": "Metais de Transição",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P10 Q2 R0",
        "eletrons": 104,
        "protons": 104,
        "neutrons": 163
    },
    "db": {
        "nome": "Dúbnio",
        "numero_atomico": 105,
        "massa_molar": 268,
        "grupo": "Metais de Transição",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P11 Q2 R0",
        "eletrons": 105,
        "protons": 105,
        "neutrons": 163
    },
    "sg": {
        "nome": "Seabórgio",
        "numero_atomico": 106,
        "massa_molar": 269,
        "grupo": "Metais de Transição",
        "descoberto_por": "Lawrence Berkeley National Laboratory",
        "camada_eletronica": "K2 L8 M18 N32 O32 P12 Q2 R0",
        "eletrons": 106,
        "protons": 106,
        "neutrons": 163
    },
    "bh": {
        "nome": "Bóhrio",
        "numero_atomico": 107,
        "massa_molar": 270,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P13 Q2 R0",
        "eletrons": 107,
        "protons": 107,
        "neutrons": 163
    },
    "hs": {
        "nome": "Hássio",
        "numero_atomico": 108,
        "massa_molar": 277,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P14 Q2 R0",
        "eletrons": 108,
        "protons": 108,
        "neutrons": 169
    },
    "mt": {
        "nome": "Meitnério",
        "numero_atomico": 109,
        "massa_molar": 278,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P15 Q2 R0",
        "eletrons": 109,
        "protons": 109,
        "neutrons": 169
    },
    "ds": {
        "nome": "Darmstádio",
        "numero_atomico": 110,
        "massa_molar": 281,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P16 Q2 R0",
        "eletrons": 110,
        "protons": 110,
        "neutrons": 171
    },
    "rg": {
        "nome": "Roentgênio",
        "numero_atomico": 111,
        "massa_molar": 282,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P17 Q2 R0",
        "eletrons": 111,
        "protons": 111,
        "neutrons": 171
    },
    "cn": {
        "nome": "Copernício",
        "numero_atomico": 112,
        "massa_molar": 285,
        "grupo": "Metais de Transição",
        "descoberto_por": "Gesellschaft für Schwerionenforschung",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q2 R0",
        "eletrons": 112,
        "protons": 112,
        "neutrons": 173
    },
    "nh": {
        "nome": "Nihônio",
        "numero_atomico": 113,
        "massa_molar": 286,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "RIKEN",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q3 R0",
        "eletrons": 113,
        "protons": 113,
        "neutrons": 173
    },
    "fl": {
        "nome": "Fleróvio",
        "numero_atomico": 114,
        "massa_molar": 289,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q4 R0",
        "eletrons": 114,
        "protons": 114,
        "neutrons": 175
    },
    "mc": {
        "nome": "Moscóvio",
        "numero_atomico": 115,
        "massa_molar": 290,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q5 R0",
        "eletrons": 115,
        "protons": 115,
        "neutrons": 175
    },
    "lv": {
        "nome": "Livermório",
        "numero_atomico": 116,
        "massa_molar": 293,
        "grupo": "Metais Pós-transição",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q6 R0",
        "eletrons": 116,
        "protons": 116,
        "neutrons": 177
    },
    "ts": {
        "nome": "Tenessino",
        "numero_atomico": 117,
        "massa_molar": 294,
        "grupo": "Halogênios",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q7 R0",
        "eletrons": 117,
        "protons": 117,
        "neutrons": 177
    },
    "og": {
        "nome": "Oganessônio",
        "numero_atomico": 118,
        "massa_molar": 294,
        "grupo": "Gases Nobres",
        "descoberto_por": "Joint Institute for Nuclear Research",
        "camada_eletronica": "K2 L8 M18 N32 O32 P18 Q8 R0",
        "eletrons": 118,
        "protons": 118,
        "neutrons": 176
    },

}
